import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { redirects } from './utils/redirects.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 8080;

// Redirect middleware
app.use((req, res, next) => {
  for (const redirect of redirects) {
    if (typeof redirect.from === 'string' && redirect.from === req.originalUrl) {
      return res.redirect(301, redirect.to);
    }
    if (redirect.from instanceof RegExp && redirect.from.test(req.originalUrl)) {
      const newPath = req.originalUrl.replace(redirect.from, redirect.to);
      return res.redirect(301, newPath);
    }
  }
  next();
});

// Serve static files from the dist directory (generated by Vite)
app.use(express.static(path.join(__dirname, 'dist')));

// Handle SPA routing: return index.html for all requests that don't match a static file
// This fixes the "Cannot GET /..." error on refresh or direct link
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
