import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import redirects from './combined_redirects.json' assert { type: 'json' };

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 8080;

// Redirect middleware
app.use((req, res, next) => {
  const redirectPath = redirects[req.url];
  if (redirectPath) {
    res.redirect(301, redirectPath);
  } else {
    next();
  }
});

// Serve static files from the dist directory (generated by Vite)
app.use(express.static(path.join(__dirname, 'dist')));

// Handle SPA routing: return index.html for all requests that don't match a static file
// This fixes the "Cannot GET /..." error on refresh or direct link
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
