
import { BrevoEmailPayload } from '@/types/models';

interface SendMagicLinkParams {
    to: string;
    token: string;
    estimate: number;
    deviceModel: string;
    lang?: string;
}

export async function sendMagicLinkEmail({ to, token, estimate, deviceModel, lang = 'fr' }: SendMagicLinkParams) {
    const apiKey = process.env.BREVO_API_KEY?.trim();
    if (!apiKey) throw new Error('BREVO_API_KEY Missing');

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://belmobile.be';
    const recoveryLink = `${baseUrl}/${lang}/resume/${token}`;

    const subjects = {
        fr: `Votre offre de ${estimate}€ pour ${deviceModel} est sauvegardée !`,
        nl: `Uw bod van ${estimate}€ voor ${deviceModel} is opgeslagen!`,
        en: `Your offer of ${estimate}€ for ${deviceModel} is saved!`,
        tr: `${deviceModel} için ${estimate}€'luk teklifiniz kaydedildi!`,
    };

    const dictionary = {
        fr: {
            greeting: "Bonjour,",
            intro: `Bonne nouvelle ! Nous avons sauvegardé votre estimation de prix pour votre <strong>${deviceModel}</strong>.`,
            labelInfo: "Estimation :",
            lockedInfo: `Cette offre est garantie pendant <strong>7 jours</strong>. Vous pouvez reprendre votre session exactement là où vous l'avez laissée :`,
            cta: "Reprendre mon estimation",
            copyLink: "Ou copiez ce lien :",
            footer: "Lien sécurisé généré par Belmobile.be"
        },
        nl: {
            greeting: "Hallo,",
            intro: `Goed nieuws! We hebben uw prijsschatting voor uw <strong>${deviceModel}</strong> opgeslagen.`,
            labelInfo: "Geschatte offerte:",
            lockedInfo: `Dit aanbod is <strong>7 dagen</strong> geldig. U kunt uw sessie precies hervatten waar u gebleven was:`,
            cta: "Mijn offerte hervatten",
            copyLink: "Of kopieer deze link:",
            footer: "Veilige link gegenereerd door Belmobile.be"
        },
        en: {
            greeting: "Hello,",
            intro: `Good news! We have successfully saved your price estimate for your <strong>${deviceModel}</strong>.`,
            labelInfo: "Estimated Offer:",
            lockedInfo: `This offer is locked for <strong>7 days</strong>. You can resume your session exactly where you left off below:`,
            cta: "Resume My Quote",
            copyLink: "Or copy this link:",
            footer: "Secure Link generated by Belmobile.be"
        },
        tr: {
            greeting: "Merhaba,",
            intro: `İyi haber! <strong>${deviceModel}</strong> için fiyat tahmininizi başarıyla kaydettik.`,
            labelInfo: "Tahmini Teklif:",
            lockedInfo: `Bu teklif <strong>7 gün</strong> boyunca geçerlidir. Kaldığınız yerden devam etmek için aşağıdaki butona tıklayın:`,
            cta: "Teklifime Devam Et",
            copyLink: "Veya bu bağlantıyı kopyalayın:",
            footer: "Belmobile.be tarafından oluşturulan güvenli bağlantı"
        }
    };

    const t = dictionary[lang as keyof typeof dictionary] || dictionary.en;
    const subject = subjects[lang as keyof typeof subjects] || subjects.en;

    // TODO: Create a nice HTML template. For now, a clean text-based HTML.
    const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px;">
        <div style="text-align: center; margin-bottom: 20px;">
             <h1 style="color: #4F46E5;">Belmobile.be</h1>
        </div>
        <h2 style="color: #333;">${subject}</h2>
        <p>${t.greeting}</p>
        <p>${t.intro}</p>
        
        <div style="background-color: #F3F4F6; padding: 15px; border-radius: 8px; text-align: center; margin: 20px 0;">
            <p style="margin: 0; font-size: 14px; color: #666;">${t.labelInfo}</p>
            <p style="margin: 5px 0 0 0; font-size: 24px; font-weight: bold; color: #10B981;">€${estimate}</p>
        </div>

        <p>${t.lockedInfo}</p>

        <div style="text-align: center; margin: 30px 0;">
            <a href="${recoveryLink}" style="background-color: #4F46E5; color: white; padding: 14px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">${t.cta}</a>
        </div>

        <p style="color: #666; font-size: 14px;">${t.copyLink}<br/><a href="${recoveryLink}">${recoveryLink}</a></p>

        <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 30px 0;" />
        <p style="font-size: 12px; color: #999; text-align: center;">${t.footer}</p>
    </div>
    `;

    const body: BrevoEmailPayload = {
        sender: { name: "Belmobile.be", email: "info@belmobile.be" },
        to: [{ email: to }],
        subject: subject,
        htmlContent: htmlContent,
        tags: ['lead-recovery']
    };

    const response = await fetch('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: {
            'accept': 'application/json',
            'api-key': apiKey,
            'content-type': 'application/json',
        },
        body: JSON.stringify(body)
    });

    if (!response.ok) {
        throw new Error(`Brevo Error: ${await response.text()}`);
    }

    return await response.json();
}
